title:            42 lignes à l'heure
description:      "On raisonne sur différents sujets: code, architecture et méthodes de travail. On prône l'agilité et surtout le retour sur investissement."

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: //future.42lignes.com

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Tags'
    url: '/tags'
  - title: 'Catégories'
    url: '/categories'
    type: 'categories'

authors:
  gabrielrobert:
    name: Gabriel Robert
    avatar: images/author_gabrielrobert.jpg
    email: g.robert092@gmail.com
    site: http://42lignes.com
    bio: "Développeur @spektrummedia / @snipcart / @userboat"
    twitter: kvlt_grobert
    github: gabrielrobert
  thatfrankdev:
    name: Francis Côté
    avatar: https://s.gravatar.com/avatar/a10ade3a7d2f10f5a4712d8d4fdd5d71
    email: thatfrankdev@gmail.com
    site: http://42lignes.com
    bio: "Père d'une future geek, Développeur @spektrummedia"
    twitter: thatfrankdev
    github: thatfrankdev

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/gabrielrobert"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/gabriel-robert-9229ab96"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-54342648-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Montreal
locale:      fr_CA
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
